name: it_format
description: A project created for IT-Format practice
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/fonts/
  - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
    - family: Jost
      fonts:
      - asset: 
      

